// Wires parse + buildPlan + assertPlanMatchesModel + render into one
// WorkbookRenderer for Ideal-Customer-Avatar.md — see
// problem-interview-workbook-v1.ts's header for the shared rationale. Not
// a fillable workbook (see manifests/ideal-customer-avatar-v1.ts): the
// Avatar is fully generated by Module 2, so this renders a read-only,
// styled export instead of something a Founder fills in.
import {
  assertIdealCustomerAvatarPlan,
  buildIdealCustomerAvatarPlan,
} from "@ai-catalyst/services/artifact/internal/renderers/plan/ideal-customer-avatar-plan";
import { IDEAL_CUSTOMER_AVATAR_FIELD_MANIFEST_V1 } from "@ai-catalyst/services/artifact/internal/renderers/manifests/ideal-customer-avatar-v1";
import { parseIdealCustomerAvatar } from "@ai-catalyst/services/artifact/internal/renderers/parse/ideal-customer-avatar";
import { renderWorkbookPlan } from "@ai-catalyst/services/artifact/internal/renderers/pdf/render-plan";
import type { IdealCustomerAvatarModel } from "./parse/ideal-customer-avatar.js";
import type { RequiredSection, WorkbookRenderer } from "./types.js";

// Every `##`/`###` heading in module-2.ts's IDEAL_CUSTOMER_AVATAR_TEMPLATE,
// and nothing else — renderer-template-contract.test.ts checks both
// directions against the live template. Validation Status and its five
// subsections ARE rendered (see plan/ideal-customer-avatar-plan.ts's
// validationStatus()), just compactly and at reduced visual weight — they
// are not part of the Claude Design mockup's client-facing masthead/grid/
// cards, but every confirmed heading still gets its content drawn
// somewhere rather than silently dropped.
const REQUIRED_SECTIONS: RequiredSection[] = [
  "Venture",
  "Segment",
  "Snapshot",
  "Situation",
  "Unmet Needs",
  "Functional — what they need done",
  "Emotional and social — what they feel",
  "Current Alternatives",
  "Buying Signals",
  "Tier 1 — high intent (act in 24–48 hrs)",
  "Tier 2 — building intent, nurture over 4–12 weeks",
  "Disqualifiers",
  "Core Promise",
  "Validation Status",
  "Based on observation",
  "Founder assumptions",
  "Important unknowns",
  "Contradicting evidence",
  "Highest-priority validation questions",
];

export const idealCustomerAvatarWorkbookV1: WorkbookRenderer<IdealCustomerAvatarModel> =
  {
    rendererKey: "ideal_customer_avatar_export_v1",
    rendererVersion: "1",
    mimeType: "application/pdf",
    extension: "pdf",
    downloadFilename: "Ideal-Customer-Avatar.pdf",
    requiredSections: REQUIRED_SECTIONS,
    fieldManifest: IDEAL_CUSTOMER_AVATAR_FIELD_MANIFEST_V1,
    parse: parseIdealCustomerAvatar,
    buildPlan: buildIdealCustomerAvatarPlan,
    assertPlanMatchesModel: assertIdealCustomerAvatarPlan,
    render: renderWorkbookPlan,
  };
