-- PR 2.2: OAuth 2.1 for MCP. Better Auth's legacy `mcp()` plugin (see
-- apps/web/lib/auth.ts) needs three tables — the plugin's own internal name
-- for them is `oauthApplication` / `oauthAccessToken` / `oauthConsent`, but
-- they are renamed here to an `mcp_oauth_` prefix (snake_case, matching every
-- other table in this schema) for clearer namespace separation from a
-- possible future non-MCP OAuth provider.
--
-- IMPORTANT — this rename only works because of a Better Auth 1.6.23-specific
-- gap: the `mcp()` plugin wraps `oidcProvider()` internally but discards
-- `oidcProvider`'s own schema-merging (`mergeSchema(schema, options.schema)`)
-- and returns the *raw*, un-renamed schema from its own plugin object
-- instead. `options.schema` passed to `mcp()` itself therefore has no
-- effect. The actual field/table renaming below is applied by a second,
-- schema-only synthetic plugin object declared in
-- apps/web/lib/mcp-oauth-compat/schema-override.ts and appended *after*
-- `mcp()` in the `plugins` array — Better Auth's `getAuthTables()` merges
-- every plugin's `.schema` by table key across the whole plugins array
-- (last one wins for `modelName`/per-field `fieldName`), independent of
-- what `mcp()`'s own returned plugin object contains. See that file's
-- top-of-file comment for the full explanation and the empirical
-- verification notes. Any Better Auth version bump must re-verify this
-- still holds (see apps/web/lib/mcp-oauth-compat/README.md).
--
-- Deliberately no `authentication_scheme` column: Better Auth's DCR handler
-- writes an `authenticationScheme` field that the plugin's own declared
-- schema (`plugins/oidc-provider/schema.mjs`) never declares — confirmed
-- that Better Auth's adapter write path (`transformInput`) only ever copies
-- over data keys that are declared fields in the schema, so this extra,
-- undeclared key is silently dropped on every insert, never causing an
-- error and never needing a column. `verifyMcpBearerToken`
-- (packages/services/src/mcp-auth) instead checks `type = 'public'` and
-- `client_secret` is null/empty — matching the DCR handler's own real
-- behavior (`finalClientSecret = clientType === "public" ? "" : clientSecret`).

-- =========================================================
-- 1. MCP_OAUTH_APPLICATIONS
-- Registered OAuth clients (Dynamic Client Registration, `POST /mcp/register`).
-- V1 forces every client to be a public client with no secret (see
-- apps/web/lib/mcp-oauth-compat/dcr-validation.ts) — `client_secret` must
-- always be null or empty; the column exists because Better Auth's schema
-- declares it, not because V1 ever populates it.
-- =========================================================

create table mcp_oauth_applications (
  id uuid primary key default gen_random_uuid(),

  name text not null,
  icon text,
  metadata text,

  client_id text not null,
  client_secret text,

  redirect_urls text not null,
  type text not null
    check (type in ('web', 'native', 'user-agent-based', 'public')),

  disabled boolean not null default false,

  user_id uuid
    references users(id) on delete cascade,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint mcp_oauth_applications_client_id_unique
    unique (client_id)
);

create index mcp_oauth_applications_user_id_idx
  on mcp_oauth_applications (user_id);


-- =========================================================
-- 2. MCP_OAUTH_ACCESS_TOKENS
-- Opaque bearer tokens issued by `POST /mcp/token`. `refresh_token` is
-- always generated by the plugin (even though V1 always strips
-- `offline_access` before it ever reaches this handler, so no client is
-- ever handed a redeemable refresh token) — never treat a non-null
-- refresh_token here as meaning a client can use it.
-- =========================================================

create table mcp_oauth_access_tokens (
  id uuid primary key default gen_random_uuid(),

  access_token text not null,
  refresh_token text not null,

  access_token_expires_at timestamptz not null,
  refresh_token_expires_at timestamptz not null,

  client_id text not null
    references mcp_oauth_applications(client_id) on delete cascade,
  user_id uuid
    references users(id) on delete cascade,

  scopes text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint mcp_oauth_access_tokens_access_token_unique
    unique (access_token),
  constraint mcp_oauth_access_tokens_refresh_token_unique
    unique (refresh_token)
);

create index mcp_oauth_access_tokens_client_id_idx
  on mcp_oauth_access_tokens (client_id);
create index mcp_oauth_access_tokens_user_id_idx
  on mcp_oauth_access_tokens (user_id);


-- =========================================================
-- 3. MCP_OAUTH_CONSENTS
-- Written by `POST /oauth2/consent` on every Accept — a permanent history
-- log, not a live gate: the plugin's own authorize handler never reads this
-- table to skip a repeat consent screen (server-enforced consent is instead
-- implemented by apps/web/lib/mcp-oauth-compat/hooks.ts always forcing
-- `prompt=consent`). Used by the `oauth:cleanup` CLI
-- (apps/web/scripts/oauth-cleanup.ts) to avoid deleting a Dynamic
-- Client Registration that a real user has legitimately consented to, even
-- once its access tokens have all expired and been swept.
-- =========================================================

create table mcp_oauth_consents (
  id uuid primary key default gen_random_uuid(),

  client_id text not null
    references mcp_oauth_applications(client_id) on delete cascade,
  user_id uuid not null
    references users(id) on delete cascade,

  scopes text not null,
  consent_given boolean not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index mcp_oauth_consents_client_id_idx
  on mcp_oauth_consents (client_id);
create index mcp_oauth_consents_user_id_idx
  on mcp_oauth_consents (user_id);


-- =========================================================
-- 4. MCP_OAUTH_CONSENT_CLAIMS
-- Not a Better Auth table — our own addition to close a real concurrency
-- gap in the plugin's Accept path (`findVerificationValue` ->
-- `updateVerificationByIdentifier` -> `create oauthConsent`, not atomic
-- the way token redemption's `consumeVerificationValue` is). The shared
-- `/oauth2/consent` before-hook
-- (apps/web/lib/mcp-oauth-compat/consent-validation.ts) does
-- `insert ... on conflict (consent_code_hash) do nothing` here before
-- letting the request continue to the real handler: the first concurrent
-- Accept/Deny for a given consent_code claims the row and proceeds: any
-- second concurrent attempt for the same code fails closed with a stable
-- `invalid_request` before it ever reaches the plugin. Expired rows are
-- swept by the same `oauth:cleanup` CLI that sweeps expired access tokens.
-- =========================================================

create table mcp_oauth_consent_claims (
  consent_code_hash text primary key,

  claimed_at timestamptz not null default now(),
  expires_at timestamptz not null
);
