import type { FieldManifest } from "../types.js";

// A read-only styled export, not a fillable workbook — Ideal-Customer-Avatar.md
// is fully generated by Module 2, so there is nothing left for a Founder to
// fill in. The manifest still exists (every renderer has one, per
// assert-pdf-structure.ts's contract) but is intentionally empty: one
// section, no fields.
export const IDEAL_CUSTOMER_AVATAR_FIELD_MANIFEST_V1: FieldManifest = {
  sectionPrefix: "avatar",
  sectionCount: { kind: "fixed", value: 1 },
  fields: [],
};
