export interface AuthorizationServerMetadataOptions {
  /** apps/web's own base URL (`AUTH_ISSUER_URL`) — this Authorization Server's issuer identifier. */
  issuer: string;
}

/**
 * Hand-written RFC 8414 Authorization Server Metadata document, served at
 * the true root `GET /.well-known/oauth-authorization-server` by
 * `apps/web/app/.well-known/oauth-authorization-server/route.ts`.
 *
 * Not generated by better-auth's own `mcp()` plugin for a reason distinct
 * from (and more fundamental than) the Protected Resource Metadata case in
 * apps/mcp/src/well-known/protected-resource.ts: the plugin registers its
 * equivalent endpoint (`getMcpOAuthConfig`, confirmed against the compiled
 * 1.6.23 source) at the *relative* path `/.well-known/oauth-authorization-server`,
 * which Better Auth's router only ever serves under its own base path —
 * i.e. `${issuer}/api/auth/.well-known/oauth-authorization-server`, not
 * `${issuer}/.well-known/oauth-authorization-server`. RFC 8414 §3 requires
 * the document live at the literal `/.well-known/...` path relative to the
 * issuer's *origin* whenever the issuer URL itself has no path component
 * (ours never does), so no client that only knows the issuer URL — which is
 * the entire point of `.well-known` discovery — could ever find Better
 * Auth's own copy of this document. This one, hand-written and served from
 * this Next.js app's own true root, is the one every MCP client actually
 * discovers.
 *
 * Deliberately narrower than the plugin's own generic defaults
 * (`getMCPProviderMetadata`) in several fields — `scopes_supported`,
 * `grant_types_supported`, and `token_endpoint_auth_methods_supported` all
 * advertise only what this compatibility profile's hardening hooks
 * (apps/web/lib/mcp-oauth-compat/hooks.ts, dcr-validation.ts) actually
 * allow through, not what the underlying plugin would accept before those
 * hooks run. Both grants listed here are real and reachable: `/mcp/token`'s
 * before-hook validates each one and rejects everything else. `userinfo_endpoint`/`jwks_uri` are omitted entirely (both
 * optional per RFC 8414) — this profile never issues an OIDC ID token (no
 * `jwt()` plugin; see infra/database/better-auth-schema-compatibility.md),
 * so advertising either would describe a capability that doesn't exist.
 */
export function buildAuthorizationServerMetadata(
  options: AuthorizationServerMetadataOptions,
): Record<string, unknown> {
  const { issuer } = options;
  // Better Auth's actual endpoints, still served under its own /api/auth
  // base path — only the discovery *document itself* needs to live at the
  // true root; every endpoint it points to is unaffected.
  const base = `${issuer}/api/auth`;

  return {
    issuer,
    authorization_endpoint: `${base}/mcp/authorize`,
    token_endpoint: `${base}/mcp/token`,
    registration_endpoint: `${base}/mcp/register`,
    // Not under `${base}` like the three above: Better Auth's `[...all]`
    // catch-all owns `/api/auth`, and this endpoint is ours
    // (apps/web/app/api/mcp/revoke/route.ts). RFC 8414 places no path
    // constraint on it, and a client that reads this document does not
    // care where it lives.
    //
    // Advertised so a disconnect in the AI client has somewhere to land.
    // Without it, removing the connector was purely client-side: the
    // token stayed live and this server went on treating the Founder as
    // connected until it expired.
    revocation_endpoint: `${issuer}/api/mcp/revoke`,
    revocation_endpoint_auth_methods_supported: ["none"],
    // `offline_access` is listed because it is genuinely granted on every
    // authorization — a client reading this document should be able to see
    // that it will receive a refresh token, even though the /mcp/authorize
    // hook grants that scope whether or not the client asks for it.
    scopes_supported: ["mcp:connect", "offline_access"],
    response_types_supported: ["code"],
    response_modes_supported: ["query"],
    grant_types_supported: ["authorization_code", "refresh_token"],
    token_endpoint_auth_methods_supported: ["none"],
    code_challenge_methods_supported: ["S256"],
  };
}
