import type { ProgramContent } from "../types.js";

// versionNumber/versionLabel are fixed constants — versionLabel is the upsert lookup key.
// Stay at 1/"v1" for living V1; bump only after db:freeze starts a new frozen generation.
// releaseNotes below is the in-place changelog for this row, not per-edit program_versions.
const V1_CHANGELOG = [
  "## Modules 1-7 sequenced; Proof retired; interviews become uploaded documents",
  "The full sequence is now seeded: Pressure-Test, Target Customer, Problem & Five Whys, Solution, ",
  "Epics & user stories, Competitive analysis, Business model. Module 4 is Solution ",
  '("module-04-solution-statement", producing North-Star.md and Feature-Benefit-Map.md); Proof ',
  '("module-04-evidence-of-unmet-need") is archived, and Modules 5-7 replace the label-only ',
  "placeholders that previously sat at those positions. Every entry below this one describes Module ",
  "4 as Proof and is kept as history, not as a description of current behaviour.",
  "",
  "Structured interview intake is gone with it. There is no website form, no five-interview floor ",
  "enforced in the database, no confirmed Interview-Evidence.md artefact and no evidence snapshot ",
  "pinned onto an attempt — interview_activities, interview_records and ",
  "module_attempts.source_interview_evidence_artifact_id are dropped. Founders instead upload ",
  "interview notes, research and any other prep as documents on a module's Work step ",
  "(module_prep_documents); the assistant reads them through get_module_context and the new ",
  "get_prep_document tool. Files are stored as-is and never parsed server-side, so text formats ",
  "come back inline and binaries come back readable:false — the assistant is required to say it ",
  "cannot read a file rather than infer contents from the filename. Uploaded material carries no ",
  "automatic evidence grade: it stays an assumption until the Founder confirms what it supports.",
  "",
  "## Module 4 QA — source prerequisite, submit set, Evidence PDF, prompt fidelity",
  "interview_evidence is optional for official validators (is_required=false); complete_module still ",
  "requires this Attempt's pinned source_interview_evidence_artifact_id. Submit interviews persists ",
  "evidence_status=submitted before Confirm evidence. evidence_of_unmet_need gains ",
  "evidence_of_unmet_need_html_v1 (HTML→Gotenberg PDF). Facilitator/generator v3: free-text review ",
  "(no Save-as-is), quantitative fidelity, no claim re-strengthening, Level 4 unprompted / Level 5 ",
  "paid-or-binding.",
  "",
  "## Module 4 — website interview evidence, then Claude",
  "Module 3 still prepares the Interview Guide (questions snapshotted at confirm). Module 4 opens ",
  "with website Steps 1–2 (record interviews → confirm Interview-Evidence.md); Continue in Claude ",
  "only after confirm. Claude runs Analyse / Decide / Plan against one pinned evidence snapshot per ",
  "attempt. Printable PDFs (Interview Guide, Verdict, ICA, 30-Day Roadmap) render via HTML→Gotenberg ",
  "(interview_guide_html_v1 / pressure_test_verdict_html_v1 / ideal_customer_avatar_html_v1 / ",
  "validation_roadmap_html_v1). Legacy pdf-lib renderer keys remain registered for in-flight Runs.",
  "",
  "## Ideal Customer Avatar gains a styled PDF export",
  "Module 2's Ideal-Customer-Avatar.md is now also downloadable as an on-demand, never-stored PDF ",
  '("?format=workbook") ported from a Claude Design mockup — a navy masthead, four-column Snapshot ',
  "band, and tiered Buying Signal cards, in place of the plain Markdown. Read-only: there is nothing ",
  "for a Founder to fill in, since Module 2 fully generates this artefact. renderer_key is now ",
  '"ideal_customer_avatar_export_v1". The template\'s internal Validation Status section is still ',
  "rendered (compactly, muted) rather than dropped, per renderer-template-contract.test.ts's reverse ",
  "check.",
  "",
  "## Operational workbooks — Modules 3 and 4 gain a fillable PDF renderer",
  "Problem-Interview-Guide.md and Validation-Roadmap-30-Day.md are now also downloadable as an ",
  'on-demand, never-stored fillable PDF ("?format=workbook") alongside the existing Markdown ',
  "download — a Founder-facing operational copy for the pen-and-paper/typing work these two ",
  "artefacts exist to drive, while the Markdown in storage stays the sole record either module ever ",
  'reads. problem_interview_guide\'s renderer_key is now "problem_interview_workbook_v1" and ',
  "validation_roadmap_30_day's is \"validation_roadmap_workbook_v1\"; every other artefact's ",
  "renderer_key stays null. A filled workbook is never uploaded back and never becomes an artifact ",
  "version. evidence_facilitator gained one clarification alongside this: a workbook's ticked Pass ",
  "Bar/Kill Criteria boxes, if a Founder carries them into Interview-Notes.md, are the Founder's ",
  "contemporaneous observation to weigh against the written notes for that interview — never the ",
  "grading verdict on their own.",
  "",
  "## Living V1 rollout — content_lock becomes 'mutable'",
  "Every prompt/content edit used to require publishing a brand-new program_version, which a Founder ",
  "already mid-Run never saw (program_versions binds at Run creation and never moves — see that column's ",
  "own comment). That meant shipping a fix and having real Founders testing the product were mutually ",
  "exclusive. From this point on, while content_lock='mutable', the content-seed reconciler can edit ",
  "Modules/Questions/Artifact Definitions/Prompts of this already-published program_version in place, and ",
  "every Founder Run's program_run_modules is kept in sync automatically — a missing Module is front-filled, ",
  "a renamed/reordered one is updated, and nothing already unlocked is ever re-locked (see ",
  "workflow/internal/reconcile-run-modules.ts) — the next time getOrCreateProgramRun runs for that Founder. ",
  "`pnpm db:freeze` ends the living period for good and restores the original bound-at-creation semantics for ",
  "whatever version comes after.",
  "",
  "Staging and production were reset (every prior program_version, and every Run/Founder bound to one, was ",
  "wiped — see packages/db/src/reset.ts) rather than migrated in place: collapsing six already-diverged content ",
  "revisions (v1 through v6) into a single living v1 row is not a safe automatic migration.",
  "",
  '## Carried over from the old program_versions v6 ("v6-interview-notes-source-of-truth")',
  "Module 4 previously saved Interview-Notes.md in Block 1 and then graded the rest of the Module from ",
  "`evidence_additions`, which the facilitator itself describes as a deliberately lossy set of extracts — a ",
  "Module resumed in a new chat a week later had no complete copy of the interviews left. v6 inverted that: the ",
  "file is the record, the extracts are an index into it. evidence_facilitator orders the save ahead of every ",
  "Response (readable notes -> normalise -> save_artifact -> confirm success -> save_founder_input), stops the ",
  "Module if that save fails rather than continuing from the conversation copy, requires every later block and ",
  "every resume to re-read the file with get_artifact, and warns that Interview-Notes.md needs this Module's ",
  "own attemptId while Module 3's Problem-Interview-Guide.md needs Module 3's. evidence_artifact_generator reads ",
  "the file back before generating, so quotations come from the record. interview_notes moved to sequence_index ",
  "1 and the two graded outputs to 2 and 3, so sequence order describes when each artefact happens; what a ",
  "Module is summarised by is its first *required* Artifact (apps/web's headlineArtifact), not its first row.",
].join("\n");

export const PROGRAM_CONTENT: ProgramContent = {
  programKey: "founder-toolkit-v1",
  programName: "AI Catalyst Founder Toolkit",
  programDescription:
    "The single V1 Program: a skill-first founder workflow from raw idea to validation-ready plan.",
  versionNumber: 1,
  versionLabel: "v1",
  versionName: "Founder Toolkit V1 (living)",
  versionDescription:
    "The living V1 content set: Modules, Questions, Artifact Definitions, and Prompts evolve in place " +
    "(content_lock='mutable') until V1 is judged complete and frozen. See releaseNotes for the changelog " +
    "of what changed and when.",
  contentLock: "mutable",
  releaseNotes: V1_CHANGELOG,
};
