// buildPlan for ideal_customer_avatar_export_v1: turns a confirmed
// IdealCustomerAvatarModel into a WorkbookRenderPlan. Ported from the
// "Ideal Customer Avatar.dc.html" Claude Design mockup (navy masthead,
// four-column Snapshot band, accent-bordered Situation callout, two-column
// Unmet Needs, tiered Buying Signal cards, Disqualifiers + Core Promise
// band) — see plan/interview-workbook-plan.ts's header for the shared
// architecture note. Unlike that renderer this one has no fields at all:
// the Avatar is fully generated by Module 2, so every pixel here is either
// locked content or a background fill (see types.ts's RectFillEntry).
//
// The mockup is authored in CSS px at 96dpi; PDF points are 72dpi, so every
// dimension lifted from it (margins, font sizes, paddings) is pre-converted
// by the same 0.75 ratio a browser uses rendering px onto pt, not re-guessed
// at PDF scale. No serif or monospace face is embedded (only Noto Sans
// regular/bold, per pdf/embed-fonts.ts) — the mockup's Source Serif
// headline and IBM Plex Mono micro-labels are both approximated in Noto
// Sans; the layout, colour and hierarchy are the faithful part.
import { BOLD_FONTKIT_FONT, REGULAR_FONTKIT_FONT } from "@ai-catalyst/services/artifact/internal/renderers/pdf/embed-fonts";
import { A4, LayoutBuilder } from "@ai-catalyst/services/artifact/internal/renderers/pdf/layout-builder";
import { assertAllPresent, assertFooterOnEveryPage, assertNoPlaceholderText } from "@ai-catalyst/services/artifact/internal/renderers/plan/shared-assertions";
import type { IdealCustomerAvatarModel } from "../parse/ideal-customer-avatar.js";
import type { Provenance, WorkbookRenderPlan } from "../types.js";

type RGB = { r: number; g: number; b: number };

const WHITE: RGB = { r: 1, g: 1, b: 1 };
const NAVY: RGB = { r: 0x1f / 255, g: 0x3a / 255, b: 0x5f / 255 };
const NAVY_MUTED_TEXT: RGB = { r: 0xa9 / 255, g: 0xbb / 255, b: 0xd0 / 255 };
const NAVY_BODY_TEXT: RGB = { r: 0xc9 / 255, g: 0xd6 / 255, b: 0xe4 / 255 };
const ACCENT: RGB = { r: 0xc2 / 255, g: 0x41 / 255, b: 0x0c / 255 };
const CARD_BG: RGB = { r: 0xf1 / 255, g: 0xf5 / 255, b: 0xf9 / 255 };
const GRID_BORDER: RGB = { r: 0xd8 / 255, g: 0xe0 / 255, b: 0xea / 255 };
const MUTED_LABEL: RGB = { r: 0x64 / 255, g: 0x74 / 255, b: 0x8b / 255 };
const INK: RGB = { r: 0x1a / 255, g: 0x1a / 255, b: 0x1a / 255 };
const MUTED_BODY: RGB = { r: 0x6b / 255, g: 0x72 / 255, b: 0x80 / 255 };
const MARGIN = 30; // 40px design margin * 0.75
const MICRO_SIZE = 6.5;

/**
 * A micro-label line (tracked-uppercase style in the mockup, plain small
 * bold caps here — see this file's header on the missing mono face) with
 * a value block beneath it. Returns the total height consumed from `topY`
 * downward, so the caller can place whatever comes next at
 * `topY - returnedHeight`.
 */
function labelAndValue(
  layout: LayoutBuilder,
  role: string,
  label: string,
  text: string,
  topY: number,
  x: number,
  width: number,
  textSize: number,
  textColor: RGB,
  labelColor: RGB,
): number {
  layout.lockedText(`${role}.label`, label.toUpperCase(), { size: MICRO_SIZE, bold: true, color: labelColor }, { x, y: topY });
  const labelHeight = layout.linePitch(MICRO_SIZE, true);
  const valueTop = topY - labelHeight - 4;
  layout.lockedText(role, text, { size: textSize, color: textColor }, { x, y: valueTop, maxWidth: width });
  const valueHeight = layout.measuredHeight(text, textSize, width);
  return labelHeight + 4 + valueHeight;
}

/** A section micro-label with a hairline rule beneath it. Returns the total height consumed from `topY`. */
function sectionRule(layout: LayoutBuilder, role: string, label: string, topY: number): number {
  layout.lockedText(`${role}.label`, label.toUpperCase(), { size: MICRO_SIZE, bold: true, color: MUTED_LABEL }, { x: layout.margin, y: topY });
  const ruleY = topY - layout.linePitch(MICRO_SIZE, true) - 5;
  layout.rectAt({ x: layout.margin, y: ruleY, width: layout.usableWidth, height: 0.75 }, INK);
  return topY - ruleY + 7;
}

/** A bulleted list, one lockedText entry per item. Returns the total height consumed from `topY`. */
function bulletList(
  layout: LayoutBuilder,
  rolePrefix: string,
  items: string[],
  topY: number,
  x: number,
  width: number,
  size: number,
  color: RGB,
): number {
  let y = topY;
  for (let i = 0; i < items.length; i += 1) {
    const text = `·  ${items[i]}`;
    layout.lockedText(`${rolePrefix}.${i + 1}`, text, { size, color }, { x, y, maxWidth: width });
    y -= layout.measuredHeight(text, size, width) + 4;
  }
  return topY - y;
}

/** Full-bleed navy masthead: venture name, title, segment. */
function header(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  layout.setFooterLabel("Ideal Customer Avatar");
  const innerX = MARGIN;
  const innerWidth = A4.width - innerX * 2;
  const top = layout.y;

  let y = top - 15;
  // Drawn verbatim, never uppercased — unlike every other micro-label in
  // this file (fixed renderer chrome like "SEGMENT"/"WHO"), this one is
  // model-derived content, and assertIdealCustomerAvatarPlan checks it
  // against the confirmed venture name exactly as written.
  layout.lockedText("header.venture", model.ventureName, { size: 8.5, bold: true, color: NAVY_MUTED_TEXT }, { x: innerX, y });
  y -= layout.linePitch(8.5, true) + 8;

  const titleSize = 22;
  layout.lockedText("header.title", "Ideal Customer Avatar", { size: titleSize, bold: true, color: WHITE }, { x: innerX, y, maxWidth: innerWidth });
  y -= layout.linePitch(titleSize, true) + 8;

  const segmentHeight = labelAndValue(
    layout,
    "header.segment",
    "Segment",
    model.segment,
    y,
    innerX,
    innerWidth,
    10,
    NAVY_BODY_TEXT,
    NAVY_MUTED_TEXT,
  );
  y -= segmentHeight + 15;

  layout.rectAt({ x: 0, y, width: A4.width, height: top - y }, NAVY);
  layout.y = y - 11;
}

function snapshotGrid(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  const cols: Array<{ label: string; value: string }> = [
    { label: "Who", value: model.snapshot.who },
    { label: "Where", value: model.snapshot.where },
    { label: "Stage", value: model.snapshot.stage },
    { label: "Raise", value: model.snapshot.raise },
  ];
  const colWidth = layout.usableWidth / 4;
  const colPad = 10;
  const innerWidth = colWidth - colPad * 2;
  const valueHeights = cols.map((col) => layout.measuredHeight(col.value, 8.5, innerWidth));
  const bandHeight = 12 + layout.linePitch(MICRO_SIZE, true) + 4 + Math.max(...valueHeights) + 12;

  layout.ensure(bandHeight);
  const top = layout.y;
  layout.rectAt({ x: 0, y: top - bandHeight, width: A4.width, height: bandHeight }, CARD_BG);
  layout.rectAt({ x: 0, y: top - bandHeight, width: A4.width, height: 0.75 }, GRID_BORDER);

  cols.forEach((col, i) => {
    const x = layout.margin + i * colWidth;
    if (i > 0) {
      layout.rectAt({ x, y: top - bandHeight, width: 0.75, height: bandHeight }, GRID_BORDER);
    }
    labelAndValue(
      layout,
      `snapshot.${col.label.toLowerCase()}`,
      col.label,
      col.value,
      top - 12,
      x + colPad,
      innerWidth,
      8.5,
      INK,
      MUTED_LABEL,
    );
  });

  layout.y = top - bandHeight - 11;
}

function situation(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  const labelWidth = 60;
  const textX = layout.margin + 12 + labelWidth;
  const textWidth = layout.usableWidth - 12 - labelWidth;
  const height = layout.measuredHeight(model.situation, 9, textWidth);
  layout.ensure(height + 12);

  const top = layout.y;
  layout.rectAt({ x: layout.margin, y: top - height - 2, width: 1.5, height: height + 2 }, ACCENT);
  layout.lockedText("situation.label", "Situation", { size: MICRO_SIZE, bold: true, color: ACCENT }, { x: layout.margin + 12, y: top });
  layout.lockedText("situation", model.situation, { size: 9, color: INK }, { x: textX, y: top, maxWidth: textWidth });

  layout.y = top - height - 15;
}

function unmetNeeds(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  layout.ensure(60);
  const headingHeight = sectionRule(layout, "unmet_needs", "Unmet needs", layout.y);
  const top = layout.y - headingHeight;

  const gutter = 18;
  const colWidth = (layout.usableWidth - gutter) / 2;
  const rightX = layout.margin + colWidth + gutter;

  const headingSize = 10.5;
  layout.lockedText("unmet_needs.functional_heading", "Functional — what they need done", { size: headingSize, bold: true, color: NAVY }, {
    x: layout.margin,
    y: top,
    maxWidth: colWidth,
  });
  const leftListTop = top - layout.linePitch(headingSize, true) - 6;
  const leftHeight = bulletList(layout, "unmet_needs.functional", model.unmetNeeds.functional, leftListTop, layout.margin, colWidth, 8.5, INK);

  layout.lockedText("unmet_needs.emotional_heading", "Emotional & social — what they feel", { size: headingSize, bold: true, color: NAVY }, {
    x: rightX,
    y: top,
    maxWidth: colWidth,
  });
  const rightListTop = top - layout.linePitch(headingSize, true) - 6;
  const rightHeight = bulletList(layout, "unmet_needs.emotional", model.unmetNeeds.emotional, rightListTop, rightX, colWidth, 8.5, INK);

  const consumed = layout.linePitch(headingSize, true) + 6 + Math.max(leftHeight, rightHeight);
  layout.y = top - consumed - 11;
}

function buyingSignalCard(
  layout: LayoutBuilder,
  top: number,
  cardHeight: number,
  role: string,
  x: number,
  width: number,
  title: string,
  items: string[],
  accentColor: RGB,
): void {
  const pad = 11;
  const innerWidth = width - pad * 2;
  layout.rectAt({ x, y: top - cardHeight, width, height: cardHeight }, CARD_BG);
  layout.rectAt({ x, y: top, width, height: 1.5 }, accentColor);
  layout.lockedText(`${role}.title`, title, { size: 9, bold: true, color: accentColor }, { x: x + pad, y: top - pad, maxWidth: innerWidth });
  const itemsTop = top - pad - layout.linePitch(9, true) - 6;
  bulletList(layout, role, items, itemsTop, x + pad, innerWidth, 8.5, INK);
}

function buyingSignals(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  layout.ensure(60);
  const headingHeight = sectionRule(layout, "buying_signals", "Buying signals — behaviours and actions", layout.y);
  const gutter = 20;
  const colWidth = (layout.usableWidth - gutter) / 2;
  const rightX = layout.margin + gutter + colWidth;

  const pad = 11;
  const titleHeight = layout.linePitch(9, true);
  const cardHeightFor = (items: string[]) =>
    pad +
    titleHeight +
    6 +
    items.reduce((sum, item) => sum + layout.measuredHeight(`·  ${item}`, 8.5, colWidth - pad * 2) + 4, 0) +
    pad;

  const cardHeight = Math.max(cardHeightFor(model.buyingSignals.tier1), cardHeightFor(model.buyingSignals.tier2));
  const top = layout.y - headingHeight;

  buyingSignalCard(layout, top, cardHeight, "buying_signals.tier1", layout.margin, colWidth, "Tier 1 — high intent, act within 24–48 hours", model.buyingSignals.tier1, ACCENT);
  buyingSignalCard(layout, top, cardHeight, "buying_signals.tier2", rightX, colWidth, "Tier 2 — building intent, nurture over 4–12 weeks", model.buyingSignals.tier2, NAVY);

  layout.y = top - cardHeight - 11;
}

function disqualifiersAndPromise(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  const labelWidth = 88;
  const textX = layout.margin + labelWidth;
  const textWidth = layout.usableWidth - labelWidth;
  const line = model.disqualifiers.join("  ·  ");
  const disqualifiersHeight = layout.measuredHeight(line, 8.5, textWidth);
  layout.ensure(disqualifiersHeight + 12);

  const disqualifiersTop = layout.y;
  layout.lockedText("disqualifiers.label", "Disqualifiers", { size: MICRO_SIZE, bold: true, color: ACCENT }, { x: layout.margin, y: disqualifiersTop });
  layout.lockedText("disqualifiers", line, { size: 8.5, color: MUTED_BODY }, { x: textX, y: disqualifiersTop, maxWidth: textWidth });
  layout.y = disqualifiersTop - Math.max(layout.linePitch(MICRO_SIZE, true), disqualifiersHeight) - 10;

  const promiseHeight = layout.measuredHeight(model.corePromise, 9.5, textWidth);
  const bandHeight = promiseHeight + 24;
  layout.ensure(bandHeight);
  const top = layout.y;
  layout.rectAt({ x: 0, y: top - bandHeight, width: A4.width, height: bandHeight }, NAVY);
  layout.lockedText("core_promise.label", "Core promise", { size: MICRO_SIZE, bold: true, color: NAVY_MUTED_TEXT }, { x: layout.margin, y: top - 12 });
  layout.lockedText("core_promise", model.corePromise, { size: 9.5, color: WHITE }, { x: textX, y: top - 12, maxWidth: textWidth });
  layout.y = top - bandHeight;
}

/**
 * Compact, muted-grey, de-emphasised relative to everything above — the
 * confirmed template's own wording calls this "a current snapshot, not a
 * final validation verdict", which is internal/administrative context
 * rather than the client-facing Avatar content the mockup's masthead,
 * grid and cards are built for. Rendered rather than dropped anyway (see
 * IdealCustomerAvatarModel's comment).
 */
function validationStatus(layout: LayoutBuilder, model: IdealCustomerAvatarModel): void {
  layout.ensure(60);
  const headingHeight = sectionRule(layout, "validation_status", "Validation status (internal — not a verdict)", layout.y);
  const top = layout.y - headingHeight;

  const rows: Array<[string, string]> = [
    ["Current level", model.validationStatus.currentLevel],
    ["Based on observation", model.validationStatus.basedOnObservation],
    ["Founder assumptions", model.validationStatus.founderAssumptions],
    ["Important unknowns", model.validationStatus.importantUnknowns],
    ["Contradicting evidence", model.validationStatus.contradictingEvidence],
    ["Highest-priority questions", model.validationStatus.highestPriorityQuestions],
  ];

  let y = top;
  rows.forEach(([label, value], i) => {
    const text = `${label}: ${value}`;
    layout.lockedText(`validation_status.${i + 1}`, text, { size: 7.5, color: MUTED_BODY }, {
      x: layout.margin,
      y,
      maxWidth: layout.usableWidth,
    });
    y -= layout.measuredHeight(text, 7.5, layout.usableWidth) + 3;
  });

  layout.y = y;
}

export function buildIdealCustomerAvatarPlan(
  model: IdealCustomerAvatarModel,
  provenance: Provenance,
): WorkbookRenderPlan {
  const layout = new LayoutBuilder(REGULAR_FONTKIT_FONT, BOLD_FONTKIT_FONT, { margin: MARGIN });
  header(layout, model);
  snapshotGrid(layout, model);
  situation(layout, model);
  unmetNeeds(layout, model);
  buyingSignals(layout, model);
  disqualifiersAndPromise(layout, model);
  validationStatus(layout, model);

  const { pages, fields, lockedContent, rects } = layout.toPlanParts();
  return { pages, fields, lockedContent, rects, provenance };
}

/**
 * The only place content equality between the confirmed
 * IdealCustomerAvatarModel and the plan is checked — see
 * interview-workbook-plan.ts's header for the shared rationale.
 */
export function assertIdealCustomerAvatarPlan(plan: WorkbookRenderPlan, model: IdealCustomerAvatarModel): void {
  assertFooterOnEveryPage(plan);
  assertNoPlaceholderText(plan);

  assertAllPresent(plan, [model.ventureName], "venture name");
  assertAllPresent(plan, [model.segment], "segment");
  assertAllPresent(
    plan,
    [model.snapshot.who, model.snapshot.where, model.snapshot.stage, model.snapshot.raise],
    "snapshot field",
  );
  assertAllPresent(plan, [model.situation], "situation");
  assertAllPresent(plan, model.unmetNeeds.functional, "functional unmet need");
  assertAllPresent(plan, model.unmetNeeds.emotional, "emotional unmet need");
  assertAllPresent(plan, model.buyingSignals.tier1, "Tier 1 buying signal");
  assertAllPresent(plan, model.buyingSignals.tier2, "Tier 2 buying signal");
  assertAllPresent(plan, model.disqualifiers, "disqualifier");
  assertAllPresent(plan, [model.corePromise], "core promise");
  assertAllPresent(
    plan,
    [
      model.validationStatus.currentLevel,
      model.validationStatus.basedOnObservation,
      model.validationStatus.founderAssumptions,
      model.validationStatus.importantUnknowns,
      model.validationStatus.contradictingEvidence,
      model.validationStatus.highestPriorityQuestions,
    ],
    "validation status field",
  );
}
