export interface ProtectedResourceMetadataOptions {
  /** This Resource Server's own canonical resource identifier — its `/mcp` endpoint's absolute URL. */
  resourceUrl: string;
  /** apps/web's Authorization Server base URL (its Better Auth `AUTH_ISSUER_URL`). */
  authorizationServerUrl: string;
}

/**
 * RFC 9728 Protected Resource Metadata served at
 * `GET /.well-known/oauth-protected-resource` by apps/mcp (Resource Server).
 *
 * Hand-written for split AS (apps/web) / RS (apps/mcp) deployment — not
 * generated by better-auth's combined-process mcp() metadata helper.
 */
export function buildProtectedResourceMetadata(
  options: ProtectedResourceMetadataOptions,
): Record<string, unknown> {
  return {
    resource: options.resourceUrl,
    authorization_servers: [options.authorizationServerUrl],
    scopes_supported: ["mcp:connect"],
    bearer_methods_supported: ["header"],
  };
}
