export interface ProtectedResourceMetadataOptions {
  /** This Resource Server's own canonical resource identifier — its `/mcp` endpoint's absolute URL. */
  resourceUrl: string;
  /** apps/web's Authorization Server base URL (its Better Auth `AUTH_ISSUER_URL`). */
  authorizationServerUrl: string;
}

/**
 * Hand-written RFC 9728 Protected Resource Metadata document, served at
 * `GET /.well-known/oauth-protected-resource` by this Resource Server
 * (apps/mcp) — never by apps/web, per architecture.mdc's Authorization
 * Server / Resource Server split.
 *
 * Hand-written rather than generated by better-auth's `mcp()` plugin: that
 * plugin's own `getMCPProtectedResourceMetadata` (confirmed against the
 * compiled 1.6.23 source) is designed for a single combined AS+RS process —
 * it hardcodes both `resource` and `authorization_servers` to its own
 * origin (`ctx.context.baseURL`'s origin), which is exactly wrong for this
 * project's split architecture (apps/web is the Authorization Server,
 * apps/mcp is a separate Resource Server), always advertises a `jwks_uri`
 * (meaningless for this profile's opaque tokens — see
 * infra/database/better-auth-schema-compatibility.md), and defaults
 * `scopes_supported` to the OIDC scopes this profile never issues a token
 * for. It also lives under apps/web's own `/api/auth` surface, not this
 * Resource Server's — RFC 9728 requires it be served by the Resource
 * Server itself.
 */
export function buildProtectedResourceMetadata(
  options: ProtectedResourceMetadataOptions,
): Record<string, unknown> {
  return {
    resource: options.resourceUrl,
    authorization_servers: [options.authorizationServerUrl],
    scopes_supported: ["mcp:connect"],
    bearer_methods_supported: ["header"],
  };
}
